### PR TITLE
fix issue #99 related to `ListTileTheme` 

### PR DESCRIPTION
**Pull request by zeusbaba**
fix issue #99 related to `ListTileTheme`

### CODE REVIEW

**Comment by tomarra** [comment]
Now that Flutter 2.8 is released to stable would be great to get this merged and released :)

**Comment by felix-ht** [comment]
you probably should add 
```yaml
environment:
  flutter: ^2.8.0
```
to pubspec as this will not work with old version of flutter

**Comment by zeusbaba** [comment]
> you probably should add
> 
> ```yaml
> environment:
>   flutter: ^2.8.0
> ```
> 
> to pubspec as this will not work with old versions of flutter

done

**Comment by zhelon** [comment]
can you merge and release it soon?

**Comment by zeusbaba** [comment]
while waiting for this be merged, you can use my fork;  
```
settings_ui:
    git: git://github.com/beerstorm-net/flutter-settings-ui.git  
```

**Comment by rteitge** [comment]
@zeusbaba your fork is based on dart sdk 2.8 without null safety so not usable.

**Comment by zeusbaba** [comment]
> @zeusbaba your fork is based on dart sdk 2.8 without null safety so not usable.

see why it done so https://github.com/yako-dev/flutter-settings-ui/pull/101#issuecomment-992440185

**Comment by zeusbaba** [comment]
> > @zeusbaba your fork is based on dart sdk 2.8 without null safety so not usable.
> 
> see why it done so [#101 (comment)](https://github.com/yako-dev/flutter-settings-ui/pull/101#issuecomment-992440185)

you are right, I just reverted this to null safety.

**Comment by felix-ht** [comment]
@zeusbaba you have to add `flutter: ^2.8.0` as a new line  under environment and not as part of sdk.

https://dart.dev/tools/pub/pubspec#sdk-constraints at the very bottom of the page

**Comment by fredecodes** [comment]
FYI there is already a fork of this project which has an associated pub.dev package here:
https://pub.dev/packages/flutter_settings_ui

My understanding is that the original creator of this package (yak-dev) has gone awol and is not updating the pub.dev package or merging pull requests, so one of the contributors created this fork and new package.  I will be using it going forward.

**Comment by elirehema** [comment]
Thanks @fredecodes it works

**Review by noobatwohlig — APPROVED** [review]
come on merge it! we are facing issue in new version of flutter

**Review by nohli — APPROVED** [review]

**Comment by yadaniyil** [comment]
Hey everyone. Sorry for not reviewing this PR for such a long time. The new 2.0.0 version is just published where the code is rewritten from scratch, bugs are fixed and new features and UI were added. Please check if the new version contains your bug fix and create a new PR if it's not. This package is not forgotten, alive, new features will be added and PRs will be checked in time. Thanks.

**Comment by yadaniyil** [comment]
Merged, thanks @zeusbaba.

To use the package with this fix use in pubspec.yaml:
```
settings_ui:
    git: git://github.com/yako-dev/flutter-settings-ui.git  
```

Also, consider moving to the new 2.0.0 version that will be maintained from now.

**Pull request merged**
