### PR TITLE
Add sliderTile

### PR DESCRIPTION
**Pull request by juliansteenbakker**
I've added a slider tile so that we can enable numeric input between a given value.

Screenshot_1615472310
Simulator Screen Shot - iPhone 11 - 2021-03-11 at 14 48 55

### CODE REVIEW

**Review by Akora-IngDKB — APPROVED** [review]
LGTM 👍🏾

**Comment by yadaniyil** [comment]
Conflicts

**Comment by yadaniyil** [comment]
It has a lot of compile errors

**Comment by juliansteenbakker** [comment]
I just saw that this package is migrated to null-safety. I will update this PR asap.

**Comment by juliansteenbakker** [comment]
@yadaniyil i closed because there are some major bugs right now. I'm currently fixing those and will comment and commit when I'm done.

This should **NOT** be merged right now

**Comment by yadaniyil** [comment]
Ah, got you, thanks. Please open it when it's ready

**Comment by juliansteenbakker** [comment]
@yadaniyil currently i have the following variables for the slider:
```dart
  // Values for Slider
  final double? value;
  final ValueChanged<double>? onChanged;
  final ValueChanged<double>? onChangeStart;
  final ValueChanged<double>? onChangeEnd;
  final double? min;
  final double? max;
  final int? divisions;
  final Color? activeColor;
  final Color thumbColor;
```

Do you think i should prefix this with an identifier for the slider like so?
```dart
  // Values for Slider
  final double? sliderValue;
  final ValueChanged<double>? sliderOnChanged;
  final ValueChanged<double>? sliderOnChangeStart;
  final ValueChanged<double>? sliderOnChangeEnd;
  final double? sliderMinValue;
  final double? sliderMaxValue;
  final int? sliderDivisions;
  final Color? sliderActiveColor;
  final Color sliderThumbColor;
```

**Comment by LiveRock** [comment]
I can't see the slider. What version it was incorporated?

**Pull request closed without merging**
