### PR TITLE
Allow custom physics and shrinkWrap on SettingsList

### PR DESCRIPTION
**Pull request by arthurdenner**
Hi! 👋 

Thanks for this library, really helpful!

### CODE REVIEW

**Comment by Akora-IngDKB** [comment]
This PR was mainly to add scroll physics.
But I'm thinking the `shrinkWrap` property should also be exposed too.
@arthurdenner what do you think?

**Comment by arthurdenner** [comment]
I don't mind adding extra properties if requested. 👍

**Comment by Akora-IngDKB** [comment]
I think it will be necessary in some cases so adding it is fine. 👍

**Comment by arthurdenner** [comment]
@Akora-IngDKB, I've added it.

**Comment by xJon** [comment]
Any idea whether this will be merged soon? Thanks!

**Comment by Akora-IngDKB** [comment]
> Any idea whether this will be merged soon? Thanks!

At the moment,  we cannot tell.
@yadaniyil is the one to do that job

**Comment by xJon** [comment]
@Akora-IngDKB No worries, I made it work on my end.

**Pull request merged**
